### ISSUE TITLE
Add an example for describing a list in a schema.

### ISSUE THREAD

**Issue by theklopex** [23andMe/Yamale#108]
Add the following to README.md after the section on Recursion:

##### List
You can specify a list using the Include validator.

This schema:
```yaml
person: list(min=1, include='human')
---
human:
    name: str()
    age: int()
```
Will validate this data:
```yaml
person:
  - name: Bill
    age: 50
  - name: Jill
    age: 20
  - name: Will
    age: 10
```
