### ISSUE TITLE
Schema for mapping dynamic input data

### ISSUE THREAD

**Issue by SuperSajuuk** [23andMe/Yamale#110]
So I'm using this module to help in creating a validator for my YAML configurations but running into an issue.

In one of the keys, there is a setting called "extra". Under that setting, can be an unlimited number of keys which have their own settings which relate to that specific key (the keys are always integers).

For each key under "extra", it can have the following keys:
- enabled (which is a boolean)
- events (a list containing strings)
- options (another dictionary containing two booleans: hide issuer and timestamp)

From the documentation provided, I am struggling to find a way of creating a validator that will allow these to be tested for and every method I've tried has been an error. The docs on includes are pretty confusing and seem to cause a validation error about "required key missing" even when that isn't the case.

Thanks in advance for any advice you can provide for resolving this! :)

**Comment by mechie** [comment]
Something like...
```yaml
extra: map(include('extraEntry'), key=str(), required=False)
---
extraEntry:
  enabled: bool()
  events: list(str())
  options:
    hideIssuer: bool()
    timestamp: timestamp()  # or a suitable regex

```
Should get you most of the way, I would think.
