### ISSUE TITLE
conditions for keys

### ISSUE THREAD

**Issue by vaibhavparnalia** [23andMe/Yamale#118]
Is it possible to have a condition where either of _expression_ or _cron_ must be present?

```
Schedule:
  expression: str()
  cron:
    day: str()
    hour: str()
    minute: str()
    month: str()
    week_day: str()
```

Currently I have it set as

```
Schedule:
  expression: str(required=False)
  cron:
    day: str(required=False)
    hour: str(required=False)
    minute: str(required=False)
    month: str(required=False)
    week_day: str(required=False)
```

**Comment by mildebrandt** [comment]
Hi, thanks for your interest in Yamale. You can use a couple `include` statements and the `any` validator to do this:

```
Schedule: any(include('expression'), include('cron'))
---
expression:
  expression: str()
---
cron:
  cron:
    day: str()
    hour: str()
    minute: str()
    month: str()
    week_day: str()
```
