### ISSUE TITLE
Usage Help: arbitrary keys with include as values.

### ISSUE THREAD

**Issue by vaibhavparnalia** [23andMe/Yamale#121]
I need some help with a use case.
I have a below Schema and Data. Data has key _target_tracking_scaling_policies_ which has arbitrary custom keys and their values are `include('TargetTrackingScalingPolicy')`. 

I was able to implement similar solution with _list()_ validator, but I am not able to implement validation of below data structure. I tried _map()_ but seems like that is not the right validator. Appreciate some help. Thanks!

Schema:
```
target_tracking_scaling_policies: dict(str(), include('TargetTrackingScalingPolicy'))  # this is incorrect
---
TargetTrackingScalingPolicy:
  target_value: int()
  predefined_metric: enum(
    'ASG_AVERAGE_CPU_UTILIZATION',
    'ASG_AVERAGE_NETWORK_IN',
    'ASG_AVERAGE_NETWORK_OUT',
    'ALB_REQUEST_COUNT_PER_TARGET'
    )
  cooldown: include('Duration')
  disable_scale_in: bool(required=False)
  estimated_instance_warmup: include('Duration')
```

Data
```
target_tracking_scaling_policies:
  asg_average_cpu_utilization:  # arbitrary key
    target_value: 70
    predefined_metric: ASG_AVERAGE_CPU_UTILIZATION
    estimated_instance_warmup:
      minutes: 5
    cooldown:
      seconds: 30
  alb_request_count_per_target:  # arbitrary key
    target_value: 10000
    predefined_metric: ALB_REQUEST_COUNT_PER_TARGET
    estimated_instance_warmup:
      minutes: 7
    cooldown:
      minutes: 1
  # add more TargetTrackingScalingPolicy types here
```
