### ISSUE TITLE
Enhancement: mark any(...) sub-object field as type guard for better errors

### ISSUE THREAD

**Issue by shaunc** [23andMe/Yamale#140]
Hmm... but how do you know what errors to issue with:
```
any(include('foo'), include('bar'))
---
foo:
  foo: regex('foo')
  a: str
bar:
  bar: regex('bar')
  b: str
```
For the three erroneous inputs:

1. `{'foo': 'foo', b: 'ok'}`
2. `{'bar': 'bar': a: 'ok'}`
3. `{'a': 'ok', b: 'ok'}`

Intuitively, if we know that `foo` and `bar` select for the "sub-type" then we could flag the first two as matching their respective types and the third as not matching any. But without any user indication seems hard to say wether 1 was a object of type 1 with a bad 'b' or an object of type 2 with missing 'bar' ... and so forth.

_Originally posted by @shaunc in https://github.com/23andMe/Yamale/issues/139#issuecomment-692179981_
