### ISSUE TITLE
flatten out the schema with data to an output file

### ISSUE THREAD

**Issue by saiprasanthrajavarapu** [23andMe/Yamale#142]
Is there any way we can flatten out the schema with data preferably to an out file?

**Problem Statement:**
We are using yamale in conjunction with aws cdk, our data yaml contain Infrastructure resources with properties and  schema to validate multiple data files. With many resources on aws and multiple properties for each our schema is already difficult to read for someone who only adds data.So, we are trying to find out if we can flatten out schema with each data file to provide better readability before deploying/provisioning and documentation as well.

Any direction/suggestion in this path will be helpful.

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale. 

I'm not sure I understand fully what you're looking for. Can you please provide some samples to illustrate your needs?

Thanks!

**Comment by saiprasanthrajavarapu** [comment]
Thank you for quick response @mildebrandt,

a small sample below

we are using multiple includes below to refer to different structures 
```yaml
elasticloadbalancingv2:
    application_load_balancer: include('aws_elasticloadbalancingv2.ApplicationLoadBalancer')

aws_elasticloadbalancingv2.ApplicationLoadBalancer:
  vpc: include('aws_ec2.Vpc')
  internet_facing: bool(required=False)
  add_listener:
    active_listener: include('aws_elasticloadbalancingv2.ApplicationListener') 

aws_elasticloadbalancingv2.ApplicationListener:
  port: int()
  add_certificate_arns:
    id: str()
    arns: list(str())

vpc_id: regex()

aws_ec2.Vpc:
  from_lookup:
    vpc_id: include('vpc_id')
```
goal is to flatten out the schema as below:
```yaml
 elasticloadbalancingv2:
    application_load_balancer:
      internet_facing: bool(required=False)
      vpc: regex()
      add_listener:
        active_listener:
          port: int()
          add_certificate_arns: 
            id: str()
            arns: list(str())
```
this will make it easy to show the flow of schema to someone who only works on data yaml. Is there a possibility to add method like flatten_schema().

**Comment by mildebrandt** [comment]
Ah, thanks for the example. That does help. Unfortunately, I don't think that's something we can add easily. Off the top of my head, I could see the `any` validator being really hard to flatten without making some assumptions. And there are cases of recursion to watch out for like this:

```yaml
person: include('human')
---
human:
    name: str()
    age: int()
    friend: include('human', required=False)
```

Flattening the `list` validator so that the `min` and `max` is represented correctly wouldn't really be possible....same with `map` validators with `include` validators for the value and `regex` validators for the keys. 

While your schema may be a good fit for flattening, it would not be possible to flatten every schema supported by Yamale. If you'd like to write a separate tool for your users, I'd suggest starting here:

```
import yamale
schema = yamale.make_schema('your_schema')
print(schema._schema)
print(schema.includes)
```
