### ISSUE TITLE
Validate Yaml file that includes custom tag such as '!include'

### ISSUE THREAD

**Issue by fkomlo** [23andMe/Yamale#145]
I have a yaml file that for one of the fields, the value is '!include another_file.yaml'. 
File 
```
entity:
  parent:
  attributes:
    - account_id
  attribute_sources: !include account_file.yaml
```
Schema
```
entity:
  parent: str(required=False)
  attributes: list()
  attribute_sources: ???
```

I have created a constructor that fills in the value with the yaml of the specified file and ```yaml.add_constructor('!include', construct_include, Loader)```, where construct_include is my custom constructor. However, when I call ```data = yamale.make_data('./yaml_file_im_validating')``` for later validation, it complains that a constructor could not be determined for my tag !include.
```yaml.constructor.ConstructorError: could not determine a constructor for the tag '!include'```

Any help on validating files with tags would be greatly appreciated.
