### ISSUE TITLE
Validate multiple maps with "basekeys"

### ISSUE THREAD

**Issue by lcnittl** [23andMe/Yamale#148]
First of, thanks for this nice tool!

I have the following schema:

```yaml
vehicles: list(include("car"), include("ship"))
other_irrelevant_stuff: str(required=False)
---
Base:
  name: str()
  type: enum("car", "ship")
---
car:
  base: include("Base")
  cargo: list(include("car_cargo"))
  wheels: list(include("car_wheel"))
car_cargo:
  passengers: int()
  animals: int(required=False)
car_wheel:
  total: int()
  powered: int()
---
ship:
  base: include("Base")
  cargo: list(include("ship_cargo"))
  engine_count: num()
ship_cargo:
  passengers: int()
  crew: int()
  animals: int()
```

which validates eg:

```yaml
vehicles:
  - base:
      name: Company Car
      type: car
    cargo:
      - passengers: 4
        animals: 1
      - passengers: 2
        animals: 2
    wheels:
      - total: 4
        powered: 4
      - total: 4
        powered: 2
  - base:
      name: Private Car
      type: car
    cargo:
      - passengers: 2
    wheels:
      - total: 4
        powered: 2
  - base:
      name: Ferry
      type: ship
    cargo:
      - passengers: 250
        crew: 6
        animals: 20
      - passengers: 250
        crew: 6
        animals: 20
    engine_count: 3
```

Yet, what I would rather want to have is the following:

```yaml
vehicles: list(include("car"), include("ship"))
other_irrelevant_stuff: str(required=False)
---
Base:
  name: str()
  type: enum("car", "ship")
---
car:
  include("Base")  # Include those key-val-pairs on same level as "cargo" and "wheels"
  cargo: list(include("car_cargo"))
  wheels: list(include("car_wheel"))
car_cargo:
  passengers: int()
  animals: int(required=False)
car_wheel:
  total: int()
  powered: int()
---
ship:
  include("Base")  # Include those key-val-pairs on same level as "cargo", "engine_count"
  cargo: list(include("ship_cargo"))
  engine_count: num()
ship_cargo:
  passengers: int()
  crew: int()
  animals: int()
```

where the `Base` map is merged with its including map to validate the data in this format:

```yaml
vehicles:
  - name: Company Car
    type: car
    cargo:
      - passengers: 4
        animals: 1
      - passengers: 2
        animals: 2
    wheels:
      - total: 4
        powered: 4
      - total: 4
        powered: 2
  - name: Private Car
    type: car
    cargo:
      - passengers: 2
    wheels:
      - total: 4
        powered: 2
  - name: Ferry
    type: ship
    cargo:
      - passengers: 250
        crew: 6
        animals: 20
      - passengers: 250
        crew: 6
        animals: 20
    engine_count: 3
```

Of course this does not work, because the `include("Base")` statements are missing their key.

Is there a clever way to achieve this, or is it not doable at the moment? (I could not deduce a solution from the documentation)

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale! 

There's no way to "inherit" from a "base schema" using Yamale constructs. However, YAML has a way you can do this with anchors:

```yaml
vehicles: list(include("car"), include("ship"))
other_irrelevant_stuff: str(required=False)
---
Base: &Base
  name: str()
  type: enum("car", "ship")
car:
  <<: *Base
  cargo: list(include("car_cargo"))
  wheels: list(include("car_wheel"))
car_cargo:
  passengers: int()
  animals: int(required=False)
car_wheel:
  total: int()
  powered: int()
ship:
  <<: *Base
  cargo: list(include("ship_cargo"))
  engine_count: num()
ship_cargo:
  passengers: int()
  crew: int()
  animals: int()
```

You just have to ensure that the references to the anchors are in the same document as the anchor itself. You'll notice I collapsed your last three documents into one. Hope that works for you.
