### ISSUE TITLE
Enhancement: Make schema depend on available keys

### ISSUE THREAD

**Issue by Mitmischer** [23andMe/Yamale#159]
First of all, thank you for the great package!

I have the following use case and wonder if it's already implemented or if it's missing from Yamale.

```
a:
  mode: 'one'
  one_paramsetX: '... some parameters for mode one ...'
  one_paramsetY: '... some more parameters for mode one ...'

b:
  mode: 'two'
  two_paramset: '... some parameters for mode two ...'
```

In this case, `one_paramsetX` and `one_paramsetY` are only required for object `a` and `two_params` is only required for object `b`. The decision should be based on the value of `mode`. To me, there currently seems to be no way to make this work within yamale.

A more simplified use case would be to make the "`required`ness" of some keys depend on the presence of other keys, not their values. In this case, that would work a bit the `dependencies` or `contains` rules of cerberus: https://docs.python-cerberus.org/en/stable/validation-rules.html

**Comment by mechie** [comment]
If I was approaching this with the validators included in yamale, I think something like this would work:

```yaml
thing: any(include('type_a'), include('type_b'))
---
type_a:
  mode: enum('one')
  one_paramsetX: ...
  one_paramsetY: ...

type_b:
  mode: enum('two')
  two_paramset: ...
```

If there were any shared parameters, I would write a "base" type with just those, and then [merge](https://yaml.org/type/merge.html) them into type_a and type_b.

That said, I've been using `required_if_present` and `required_if_missing` as  kwargs in a private yamale fork in order to change requiredness based on sibling nodes (not) existing, which sounds analogous to what you bring up last. Might be something to think about upstreaming.

Cerberus looks really interesting, hadn't heard of it before, thanks for bringing it up!
