### ISSUE TITLE
Document `key: list(include('custom'), str())` format

### ISSUE THREAD

**Issue by patcon** [23andMe/Yamale#16]
Would this be something you'd be willing to accept functionality to be able to validate?

```yaml
# config.yaml
apps:
  - id: com.android.foo
    url: http://example.com/com.android.foo.apk
  - id: com.android.bar
    versioncode: 123
  - com.android.baz
```

with this:

```yaml
# schema.yaml
apps: list(include('app'), str())
---
app:
  id: str()
  versioncode: int(required=False)
  url: str(required=False)
```
