### ISSUE TITLE
Generate warning in addition to errors

### ISSUE THREAD

**Issue by erdalkaraca** [23andMe/Yamale#170]
It seems the ValidationResult type only reports errors. I would need to also generate warnings based on additional criteria provided to the validators, for example:

```yaml
Book:
  title: str()
  pages: int(required=False, recommended=True)
```
Here, `Books.pages` is not required but recommended and I would like to create a warning or maybe another level of validation severity.
Is that possible given the current codebase of Yamale or would this require much effort to implement?
