### ISSUE TITLE
Abstracting schema (extend base schema) using `include`

### ISSUE THREAD

**Issue by Yu-AnChen** [23andMe/Yamale#182]
First of all, thanks for the great tool! I'm using it in my project and had some issues with the following case

```yaml
cohort young: list(include('young person'))
---
person:
  name: str()
  is_active: bool()

young person: include('person')
  age: int(min=0, max=50)

old person: include('person')
  age: int(min=51)
```

I was hoping to create derived schemas (`young person` and `old person`) from the "base schema" (`person`), and the derived schemas would look like these

```yaml
young person:
  name: str()
  is_active: bool()
  age: int(min=0, max=50)

old person:
  name: str()
  is_active: bool()
  age: int(min=51)
```

but got an error 

```python
ScannerError: mapping values are not allowed in this context
```

specifically, here are my questions - 
1. Could this be implemented? If so, could you suggest some directions that I can look into?
2. If it doesn't make much sense to implement this, how would you suggest changing my schema design?

Referencing point 4 in closed issue #8 

Thanks!
