### ISSUE TITLE
Lists with arbitrary name are unsupported

### ISSUE THREAD

**Issue by ilia-wolke7** [23andMe/Yamale#184]
Dear devs,
thanks for great tool.
Are lists with arbitrary names supported? Can't find schema for following file. How do I describe arbitrary word link03 and link13.
I have tried many combinations with str() but still find no solution. Thank you!

```
graph:
  length: 1
  list:
    - link03:
      start_node: 0
      end_node: 3

    - link13:
      start_node: 1
      end_node: 3
```

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale.

Do you control the format of this yaml? I'd suggest doing this instead:

```
graph:
  links:
    link03:
      start_node: 0
      end_node: 3
    link13:
      start_node: 1
      end_node: 3
```

Or if it MUST be a list, to do this:

```
graph:
  list:
    - name: link03
      start_node: 0
      end_node: 3

    - name: link13
      start_node: 1
      end_node: 3
```

If you don't have control over the schema, your validation rules will be a bit limited. Here's something that will work:
```
graph:
  length: int()
  list: list(include('graph_item'))

---

graph_item:
  map(int(), null(), key=str())
```

But you're unable to require that `start_node` is an integer. 

I suggest changing your yaml to one of the above examples instead, with a preference for the first example.
