### ISSUE TITLE
Alphabetical Order validator

### ISSUE THREAD

**Issue by PatrickDuncan** [23andMe/Yamale#209]
It would be nice if there was an alphabetical order validator for maps.

Success
```yaml
animals:
  rabbit: "fast"
  turtle: "slow"
```
Fail
```yaml
animals:
  turtle: "slow"
  rabbit: "fast"
```

Fail
```yaml
vehicles: 4
animals:
  rabbit: "fast"
  turtle: "slow"
```
