### ISSUE TITLE
better error message for list of different type

### ISSUE THREAD

**Issue by XiaosongWen** [23andMe/Yamale#210]
My use case I have two type type of target_discovery (`http` and `ping`), each of them have different schema, my code is:
```
target_discovery: list(include('resourcePingProvider'), include('resourceHttpProvider'))

resourcePingProvider:
  resourceProvider: str(equals="ping")
  probeMetadata: include('probeMetadata')
  ...

resourceHttpProvider:
  resourceProvider: str(equals="http")
  url: ...
```
Basically, it is checking the value of each `resourceProvider` field. However, if I input "xxxx", it gave me blow error messages, it contains other redundant infos. 
```
target_discovery.0.resourceProvider: XXXX does not equal ping
target_discovery.0.probeMetadata: Unexpected element
... ...
target_discovery.0.resourceProvider: XXXX does not equal http
target_discovery.0.url: Required field missing
... ... 
```
Is there a way that it only return something like `XXXX does not equal ping or http`?
