### ISSUE TITLE
Validation of fields in sub-levels

### ISSUE THREAD

**Issue by felipe88alves** [23andMe/Yamale#211]
I'm trying to validate a known `image` field, but it can be found under a diverse amount of different fields (which are not relevant for validation).

Example:

1. Sub-level - Global
```
values:
  global:
    image:
      repository: str()
      tag: str()
```
2. Sub-level - Controller App
```
values:
  controller:
    image:
      repository: str()
      tag: str()
```
2. Sub-level - App-B
```
values:
  app-b:
    image:
      repository: str()
      tag: str()
```

Is there a way to define an "any" field name to replace global, controller and app-b fields in the examples above?
Or perhaps skip the validation at this level but still allow the validation of the image fields underneath them?

**Comment by mildebrandt** [comment]
You need to use `include` and `map` validators. Here's a schema that would validate all of your samples (the validator for keys of a map is `str()` by default):

```
values: map(include('image_map'))
---
image_map:
  image:
    repository: str()
    tag: str()
```

However, I assume you'll want other keys than just `image` in your structure. Here's a more flexible way to do that:

```
values: map(include('value_map'))
---
value_map:
  image: include('image_map')
  type: str(required=False)
  size: int(required=False)
---
image_map:
  repository: str()
  tag: str()
```

**Comment by felipe88alves** [comment]
Hi @mildebrandt,
Thanks for the help, I hadn't really understood the `map` validator until your example.
This all seems very rigid, is this a design choice for yamale?

I actually have this image field on a variety of "levels", and the files have a number of other fields that I wish to ignore (I'm using the strict=False flag to handle that for now)
But is can I define the logic you laid out for image on different levels in a straight-forward manner?

Examples:
```
values:
  image:
    repository: str()
    tag: str()
```

```
values:
  global:
    image:
      repository: str()
      tag: str()
  random_field:
    sub: to_be_ignored
```


```
values:
  other:
    global:
      image:
        repository: str()
        tag: str()
```

**Comment by nbaju1** [comment]
I don't think Yamale is created to handle dynamic schemas, which I assume is what you are really asking for (i.e. validate this include wherever it may be defined). I believe you will have to create different schemas for all the various possibilities in your setup.

**Comment by felipe88alves** [comment]
Thanks for the feedback nbaju1.
Would this be an interesting feature to introduce? Or does it go against the tool's intent/design?

**Comment by mildebrandt** [comment]
I can't comment on whether this would be a feature that would be welcome since I'm no longer a maintainer. 

However, here's a schema that will validate all the examples so far:

```
values: include('value_map')
---
value_map:
  image: include('image_map', required=False)
  global: include('global_map', required=False)
  other: include('other_map', required=False)

other_map:
  image: include('image_map', required=False)
  global: include('global_map', required=False)

global_map:
  image: include('image_map', required=False)

image_map:
  repository: str()
  tag: str()
```

You would still need to specify the `--no-strict` flag to bypass any unexpected tags.

**Comment by felipe88alves** [comment]
Learning loads here, thanks @mildebrandt  :)

So I tried combining both suggestions you've made to fulfill my requirements.
The goal is to capture the occurrence of the `image` map, regardless of its level/indentation/location. 
The proposal is to use map() recursively to capture `image` in a number of levels/indentation/location, and subset to say that the `image` map may be found one or more times per file. 

Sample 1:
```
values:
  image:
      repository: str()
      tag: str()
  global:
    image:
      repository: str()
      tag: str()
    other:
      image:
        repository: str()
        tag: str()
```
Sample2:
```
values:
  random:
    field:
      image:
        repository: str()
        tag: str()
```

I was trying something like this, but I must be missing something.
Could you please advise again?

```
values: subset(include('first_level_image', required=False), map(include('second_level_image'), allow_empty=True), map(include('third_level_image'), allow_empty=True))
---
first_level_image:
  image: include('image_values, required=False)

second_level_image:
  image: include('image_values', required=False)

third_level_image:
  image: map(include('second_level_image'), allow_empty=True)

image_values:
  repository: str()
  tag: str()
```

Cheers
