### ISSUE TITLE
How to specify that at least one of two optional properties must be present?

### ISSUE THREAD

**Issue by Bascy** [23andMe/Yamale#214]
I have a yaml structure that contains 2 optional properties. Like:
```
IntegerMonitor:
   message: str()
   minValue: int(required=False)
   maxValue: int(required=False)
```

How can I specify that at least on of `minValue` or `maxValue`  needs to be present?

**Comment by mildebrandt** [comment]
It's a little verbose, but this is how you'd define that:

```yaml
IntegerMonitor: any(include('min_required'), include('max_required'))
---
min_required:
  message: str()
  minValue: int()
  maxValue: int(required=False)

max_required:
  message: str()
  minValue: int(required=False)
  maxValue: int()
```
