### ISSUE TITLE
Include external schema file

### ISSUE THREAD

**Issue by BasSchoutenTribe** [23andMe/Yamale#215]
Is it possible to include another external schema file into the current one without having to change the python code that executes the validation?

Background: im using Yamale from within platformio where an extra build script is added to validate yaml files against a schema configured in the projects properties file `platformio.ini`). The python build script to validate is generic of course, and will be the same for all projects, so i'm looking for a way to declare included files inside a schema.yaml file

something like this:

```yaml
sensor:
  id: include('id')
  type: str()
  mapwithproperties: include('schemafile2.yml/propertiesmap')
---
id: int(min=0, max=255)
```
