### ISSUE TITLE
How to make schema using regex / or accepting keys

### ISSUE THREAD

**Issue by dschiller** [23andMe/Yamale#216]
My yaml looks like

```yaml
sjdneh7:
  data: testdata
  option: anyoption
xbchd7:
  data: testdata
  option: anyoption
z73ue8:
  data: testdata
  option: anyoption
```

My scheme looks like

```yaml
library:
  data: str()
  option: str()
```

How can I describe the root entries ? As they are indistinguible and vari per entry I would like to know how I can describe them in the yaml schema.

When I change it to

```yaml
  data: str()
  option: str()
```

And use `--no-strict` mode, it somehow works but fails with

```shell
  data: Required field missing
  option: Required field missing
```

Is there a possibility to see the line number it fails at ?

**Comment by dschiller** [comment]
I copied all keys and now I can not find out how to ignore parent tags:

```yaml
sjdneh7: include('library')
xbchd7: include('library')
z73ue8: include('library')
---
library:
  data: str()
  option: str()
  tools:
    any: str(required=false)
```

Yaml data to validate:

```yaml
sjdneh7:
  data: testdata
  option: anyoption
xbchd7:
  data: testdata
  option: anyoption
  tools:
    any: abc
z73ue8:
  data: testdata
  option: anyoption
```

How can I make `tools` not mandatory ?

```shell
sjdneh7.tools.any: Required field missing
```

**Comment by dschiller** [comment]
Found out how it works regarding the not mandatory tags:

#### Schema.yaml
```yaml
sjdneh7: include('library')
xbchd7: include('library')
z73ue8: include('library')
---
library:
  data: str()
  option: str()
  tools: include('library_tools', required=False)
---
library_tools:
  any: str(required=false)
```

**Comment by mildebrandt** [comment]
I think something like this will work for you:

```yaml
map(include('library'))
---
library:
  data: str()
  option: str()
  tools: map(required=False)
```
