### ISSUE TITLE
Issue with using map validator "key" option with any/subset.

### ISSUE THREAD

**Issue by AndersonTaylor** [23andMe/Yamale#217]
Hello, I'm attempting to validate keys of a map match against at least one of two different validators using any or subset.

example yaml:
```
my_properties:
    one: "should pass"
    two: "should pass" 
    3: "should pass"
    four: "should fail"
```

I've tried:
```
my_properties: map(key=any(enum('one', 'two'), int()))
OR
my_properties: map(key=subset(enum('one', 'two'), int()))
```
but both options pass as valid.
Doing the same with only enum/int/other validators validates as expected.

Is this a bug, not possible, or am I just using the wrong syntax?
(on version 4.0.4)
Thanks.
