### ISSUE TITLE
Dynamic validation based on keys in data (internal reference)

### ISSUE THREAD

**Issue by idantene** [23andMe/Yamale#253]
Hey,

I have a thought for dynamic schema validation that I think is currently lacking (perhaps not too common request, though I believe it can be implemented as another validator).

In this case, I have a data YAML file where a mapping is expected. The keys may be anything the user decides, and the values are according to some predefined schema - so far, so good.

Next, at a later part in the data YAML, some other mapping occurs. Here, the value of the mapping has to relate to the keys defined earlier.

For example (a data YAML):
```yaml
metrics:
    iou:  # this can be whatever the user chooses
        name: foo
        unit: bar
        direction: up
...
results:
  - name: something
     metric: iou  # this has to be one of the keys defined under `metrics` above
     value: 59
```
