### ISSUE TITLE
[question] more readable/ yaml-like way to express lists in schema

### ISSUE THREAD

**Issue by basmevissen** [23andMe/Yamale#274]
Hi,

First thanks for creating a great tool as Yamale to validate YAML in a readable format. I choose Yamale because I want to write a schema for a complex configuration file that can both validate and document the format.

Most went pretty well, but with lists I struggle to make the schema more readable and looking like the YAML file will look like. Let me give a small example:

### Schema:
```
#Test Schema
top:
  bottom: list(include('bottom_list'), min=0, max=10)

high: list(include('high_list'), min=0, max=10)

---
bottom_list:
  val: int()
  name: str()

high_list:
  id: int()
  low: list(include('low_list'))

low_list:
  name: str()
  ip: ip()
```

### Example YAML:
```
# Test Example

top:
  bottom:
  - val: 4
    name: "four"
  - val: 8
    name: "eight"

high:
- id: 100
  low:
  - name: 'foo'
    ip: 192.168.0.1
  - name: 'bar'
    ip: 192.168.1.1
```

Is there a way I can "inline" the *_list key/value pairs inside the list() statement without to have to use the include statement?

Many thanks in advance for your help!

Bas.

**Comment by nbaju1** [comment]
Answer by gpt-5:

I looked up how Yamale handles inline object schemas. Yamale does not support defining fixed-key objects inline inside a list; only free-form maps via map(key=..., value=...). For fixed fields, you must use include() and define the mapping in a named section.

### What you can and can’t do
- map(...) in Yamale is for arbitrary dicts: map(key=str(), value=int()) etc. It does not accept fixed fields like map(val=int(), name=str()).
- To model a list of fixed-key objects, use list(include('...')) and define that object in a named block.

### Recommended structure
```yaml
# schema.yaml
top:
  bottom: list(include('bottom_item'), max=10)

high:
  list(include('high_item'), max=10)

---
bottom_item:
  val: int()
  name: str()

---
high_item:
  id: int()
  low: list(include('low_item'))

---
low_item:
  name: str()
  ip: ip()
```

- If you need a truly free-form dict with uniform types, use map(key=..., value=...) inside list(), but that won’t enforce fixed keys like val/name.

If you need inline, property-level object definitions without includes, consider a tool that supports inline “object properties” (e.g., JSON Schema, Pydantic models).

- You cannot inline fixed-key maps inside list() in Yamale; use include().
