### ISSUE TITLE
Multiple schema options in same file

### ISSUE THREAD

**Issue by Emily-144** [23andMe/Yamale#275]
Hi, I'm trying to validate a schema that includes multiple options, but when one has an error, the error messages for both types appear. This seems similar to [this suggestion](https://github.com/23andMe/Yamale/issues/139#issuecomment-692179981), but there hasn't been a solution found yet.

Here's roughly what I have:

```
item: list(include('configs'))
---
configs: any(include('config1'), include('config2'))
---
config1:
  # more options here
  config:
    title: enum('title1', none=False)
    # more options here
---
config2:
  # more options here
  config:
    title: enum('title2', none=False)
    # more options here
```

I'd like to choose config1 or config2 and only check those rules, based on what the value for title is (so, title1 or title2. Anything else could throw a separate error). Is there a way to do that? Currently, Yamale prints errors for both options whenever there is an error in one because it cannot figure out which one is supposed to match, but it would be more clear if it only printed errors for whichever title matches to avoid user confusion. Thanks!
