### ISSUE TITLE
Adding possibility to include validators

### ISSUE THREAD

**Issue by rigal-m** [23andMe/Yamale#37]
Hello,
I think it could be interesting to be able to include not only nodes but also validators in Yamale. For example:

```yaml
# [schema.yaml]

key1: include('freq_val_1')
key2: include('freq_val_2')

--- # Frequently used validators
freq_val_1: enum('str_1', 'str_2', 'str_3', 'str_4', 'str_5')
freq_val_2: map(include('a_node_with_some_very_long_name_1'), include('a_node_with_some_very_long_name_2'))
# etc...

--- # Included nodes
a_node_with_some_very_long_name_1:
  n: int()
a_node_with_some_very_long_name_2:
  x: num()
```

I can do a PR if you are interested. In this case all suggestions are welcome.
