### ISSUE TITLE
Can't Validate Keys with Dots in Them

### ISSUE THREAD

**Issue by supertylerc** [23andMe/Yamale#50]
It seems that I can't validate a YAML file if it has dots (`.`) in the key.  Looks like it's because of the flattening of keys later on, but interestingly you _can_ specify a key with dots in the schema, and Yamale will translate the schema keys with dots in them to underscores.

I worked around this in a _super_ hacky way locally with the following:

```python
from yamale import util

def sub(dic):
    new = {}
    for k, v in util.get_iter(dic):
        if util.is_iter(v):
            v = sub(v)
        if util.isstr(k):
            new[k.replace('.', '_')] = v
    return new


def parse_file(file_name, parser):
    try:
        parse = _parsers[parser.lower()]
    except KeyError:
        raise NameError('Parser "' + parser + '" is not supported\nAvailable parsers are listed below:\nPyYAML\nruamel')
    parsed = parse(file_name)
    new = []
    for x in parsed:
        new.append(sub(x))
    return new
```

This pretty much just replaces `.` with `_` in parsed YAML files, which is being done elsewhere anyway when things get flattened out.  I'm not sure if the flattening functionality that does the dot replacement could be removed with this patch, but maybe it could be.

Would you be open to a cleaned up and tested version of this in a PR?  If so, I can work on it and submit it.

My primary focus is networking, so this is useful when I need to validate a document with IP addresses or MAC addresses as a key.

**Comment by supertylerc** [comment]
Probably need an `else` after the string check to do `new[k] = v`, but not sure at the moment.

**Comment by supertylerc** [comment]
I through something a bit more formal together, and 16 tests failed.  :(  Looks like I made some assumptions that were incorrect.  I'll look into it briefly, but if it's too much effort, I'll just switch us internally to using underscores as separators for IP addresses (though I really don't want to have to do that).

**Comment by supertylerc** [comment]
Changes I made that resulted in the failing tests:

```diff
diff --git a/yamale/readers/yaml_reader.py b/yamale/readers/yaml_reader.py
index e27d858..78b5274 100644
--- a/yamale/readers/yaml_reader.py
+++ b/yamale/readers/yaml_reader.py
@@ -1,5 +1,7 @@
 from __future__ import absolute_import
 
+from yamale import util
+
 
 def _pyyaml(file_name):
     import yaml
@@ -24,9 +26,25 @@ _parsers = {
 }
 
 
+def munge_keys(dic, old_string, new_string):
+    munged_dict = {}
+    for k, v in util.get_iter(dic):
+        if util.is_iter(v):
+            v = munge_keys(v, old_string, new_string)
+        if util.isstr(k):
+            munged_dict[k.replace(old_string, new_string)] = v
+        else:
+            munged_dict[k] = v
+    return munged_dict
+
+
 def parse_file(file_name, parser):
     try:
         parse = _parsers[parser.lower()]
     except KeyError:
         raise NameError('Parser "' + parser + '" is not supported\nAvailable parsers are listed below:\nPyYAML\nruamel')
-    return parse(file_name)
+    yaml_documents = []
+    parsed_file = parse(file_name)
+    for document in parsed_file:
+        yaml_documents.append(munge_keys(document, '.', '_'))
+    return yaml_documents```

**Comment by supertylerc** [comment]
Error seems to be with nested schemas, but I'm not sure why or what I'm missing yet.  I'll try a little bit later today or next Friday.

**Comment by supertylerc** [comment]
:man_facepalming:

Was previously checking if it was iterable, which...lists are...so it was converting lists to dicts.  Fixed, all existing tests are passing.  Will add some more to test this new functionality and then submit a PR.

**Comment by supertylerc** [comment]
While writing new functional test cases, I discovered that this issue is actually more complicated than I thought.  Everything seems fine when the value is a scalar, but when it's a mapping, there's a `KeyError` that's raised.  Given this schema:

```yaml
---
ntp:
  config:
    enabled: bool()
    ntp-source-address: str()
  servers:
    "192.168.1.1":
      str: str()
    "192.168.1.2":
      str: str()
```

And this input:

```yaml
---
ntp_server_profile_generic: &ntp_profile_generic
  port: 123
  version: 3
  prefer: true
ntp:
  config:
    enabled: true
    ntp-source-address: 1.2.3.4
  servers:
    192.168.1.1:
      str: yes
    192.168.1.2:
      str: no
```

The following happens when running tests:

```
============================================================== ERRORS ===============================================================
_________________________________________ ERROR collecting yamale/tests/test_functional.py __________________________________________
yamale/tests/test_functional.py:80: in <module>
    d[key] = yamale.make_schema(get_fixture(d[key]))
yamale/yamale.py:17: in make_schema
    s = Schema(raw_schemas[0], path, validators=validators)
yamale/schema/schema.py:18: in __init__
    self._schema = self._process_schema(schema_dict, self.validators)
yamale/schema/schema.py:34: in _process_schema
    schema_flat = util.flatten(schema_dict)
yamale/util.py:41: in flatten
    child.update(flatten(dic[k], keep_iter, item_position))
yamale/util.py:41: in flatten
    child.update(flatten(dic[k], keep_iter, item_position))
yamale/util.py:41: in flatten
    child.update(flatten(dic[k], keep_iter, item_position))
E   KeyError: '192_168_1_1'
```

However, the following is successful:

Schema:

```yaml
---
ntp:
  config:
    enabled: bool()
    ntp-source-address: str()
  servers:
    "192.168.1.1": str()
    "192.168.1.2": str()
```

Input:

```yaml
---
ntp_server_profile_generic: &ntp_profile_generic
  port: 123
  version: 3
  prefer: true
ntp:
  config:
    enabled: true
    ntp-source-address: 1.2.3.4
  servers:
    192.168.1.1: abcd
    192.168.1.2: efgh
```

So the issue isn't quite where I thought it was, though my changes fix it anyway.  I'm going to submit the patch I've written as a PR, and we can talk about different ways to fix the issue in that PR.
