### ISSUE TITLE
Root level constraint.

### ISSUE THREAD

**Issue by chennupushkar** [23andMe/Yamale#61]
How do we express this in yamale? I want the constraints on topic-1 and topic-2 to be enforced only when yaml file has target-1.
```
target-1: 
  topic-1:
     a: str()
     b: str()
  topic-2:
     c: int()
     d: int() 

target-2: 
  topic-3:
     a: str()
     b: str()
  topic-4:
     c: int()
     d: int()
```

**Comment by mildebrandt** [comment]
Hi @chennupushkar, thanks for your interest in Yamale. Here's how you would do that:
```
target-1: include('target1', required=False)
target-2: include('target2', required=True)
---
target1:
  topic-1: include('topic1')
  topic-2: include('topic2')
target2:
  topic-3: include('topic3')
  topic-4: include('topic4')
---
topic1:
  a: str()
  b: str()
topic2:
   c: int()
   d: int()

topic3:
   a: str()
   b: str()
topic4:
   c: int()
   d: int()
```

I realize that's a little cumbersome due to issue #56. There's a PR in review that will make it a little better in the future:
```
target-1: include('target1', required=False)
target-2: include('target2', required=True)
---
target1:
  topic-1:
    a: str()
    b: str()
  topic-2:
     c: int()
     d: int() 

target2: 
  topic-3:
     a: str()
     b: str()
  topic-4:
     c: int()
     d: int()
```

Please use the first example for now, and keep an eye out for updates when you can do the second.
