### ISSUE TITLE
Custom key validation

### ISSUE THREAD

**Issue by Dejv456** [23andMe/Yamale#62]
Hello,

is it possible to validate custom key (**'abc'** or **'bcd'** or whatever **str()**) as below:

**Data:**
```
abc:
  type: 1
  option: a
bcd:
  type: 2
  option: b
```

**Schema:**
```
???: include('profile')
---
profile:
  type: int()
  option: str()
```

**Comment by mildebrandt** [comment]
Hi, there's a PR in review that may allow for this: https://github.com/23andMe/Yamale/pull/60

**Comment by mildebrandt** [comment]
This is available in version 2.0.

**Comment by Phidica** [comment]
Hi @mildebrandt, this may be a dumb question but... Could you please explain *how* to do this now? I couldn't spot this scenario in the readme, and I tried writing the schema like
```yaml
str(): include('profile')
---
profile:
  type: int()
  option: str()
```
but just get
```
Error validating data data.yaml with schema schema.yaml
        str(): Required field missing
```

I tried searching the repo with words like "custom" or "dynamic" but the former is a common word otherwise and the latter is nowhere to be found...
Thanks for your help.
