### ISSUE TITLE
[Feature request] "in" validator

### ISSUE THREAD

**Issue by LoveIsGrief** [23andMe/Yamale#71]
Hi,

first of all thanks for the work on this. It's very easy to use. I do have a feature request though.

It would be great if it were possible to add a validator that checks if a value is within a list provided by the user.

A simple example to illustrate what I'm talking about:

**Schema**
```yaml
map(include('category'))
---
category:
  default: in('category.tags')
  tags: list(str(), int())
```

**Data**
```yaml
rating:
  default: Unrated
  # default: must be within the user-defined tags
  # default: "LMAO" would be invalid for example
  tags:
    - Unrated
    - 1
    - 2
    - 3
    - 4
    - 5
```

Thank you
