### ISSUE TITLE
include schema if a reference is valid

### ISSUE THREAD

**Issue by abourree** [23andMe/Yamale#79]
Hello

I'd like include sub schema if a field is set to true.

Does custom validator can walk into full data tree?
If yes, how to?

my data
```yaml
a: true
b:
  c: 10
```

expecting schema
```yaml
a: bool()
b: includeIf('a', 'isTrue', 'b')
---
isTrue: enum(True)
---
b:
  c: int()
```
Regards,

Arnaud
