### ISSUE TITLE
Validate struct of dict

### ISSUE THREAD

**Issue by mflage** [23andMe/Yamale#89]
How dow I validate this yaml structure:

```
people:
  personA:
    name: Some Name
    age: Some Age
  personB:
    name: Some Other Name
    age: Some Other Age
```

The problem is that this is not a list, it will be parsed into a dict structure. In python this would then be ["people"]["personA"]["age"] for instance.

**Comment by mildebrandt** [comment]
Hi, thanks for your interest in Yamale. You can use the following schema:

```yaml
people: map(include('person'))
---
person:
  name: str()
  age: int()
```

Have fun!
