### ISSUE TITLE
Validate List of maps

### ISSUE THREAD

**Issue by eXpire163** [23andMe/Yamale#97]
No way to validate a list of maps

yaml:

```yaml
childs:
  - name: foo
    age: 3
  - name: bar
    age: 5
```

not working schema
```
childs: list(map())
```

```
childs: list(include(childs))
---
childs:
  name: str()
  age: int()
```

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale.

For your last example, don't forget to use quotes...for example:
```
childs: list(include('childs'))
---
childs:
  name: str()
  age: int()
```

As for this schema:
```
childs: list(map())
```

It validates correctly for me with the latest master and with 2.0.1. What version are you using and what is the error you're getting?
